
apiVersion: v1
kind: Service
metadata:
  name: evolveapp-service
spec:
  type: NodePort
  selector:
    app: evolveapp
  ports:
    - protocol: TCP
      port: 80             # Service port (you access it through this port internally)
      targetPort: 8080     # Container's exposed port
      nodePort: 30036      # External port on the Node (can be any unused port in 30000–32767 range)
